on:
  workflow_dispatch:
    inputs:
      deployment:
        required: true
        description: |
          Deploy a git branch to a specified AWS deployment (<integration>, <dev>, <master>, or a git tag such as 
          <v1.3.0>).
        type: string
        default: integration
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ inputs.deployment }}'
